// This file is automatically generated. Do not modify it manually.

const manifest = JSON.parse(`
{
    "id": "com.example.customers-plugin",
    "name": "Customers Plugin",
    "description": "客户化定制插件：可自定义 Mattermost 聊天窗口中的时间显示格式（如 2026-09-15 09:42），支持管理员统一配置与用户个人偏好。",
    "homepage_url": "https://github.com/example/mattermost-plugin-customers",
    "support_url": "https://github.com/example/mattermost-plugin-customers/issues",
    "icon_path": "assets/icon.svg",
    "version": "0.1.0",
    "min_server_version": "10.0.0",
    "server": {
        "executables": {
            "darwin-amd64": "server/dist/plugin-darwin-amd64",
            "darwin-arm64": "server/dist/plugin-darwin-arm64",
            "linux-amd64": "server/dist/plugin-linux-amd64",
            "linux-arm64": "server/dist/plugin-linux-arm64",
            "windows-amd64": "server/dist/plugin-windows-amd64.exe"
        },
        "executable": ""
    },
    "webapp": {
        "bundle_path": "webapp/dist/main.js"
    },
    "settings_schema": {
        "header": "配置 Customers Plugin 的时间显示能力。管理员在此设置全站默认值，用户可在「设置 → 插件 → Customers Plugin」中按个人偏好覆盖（取决于下面是否允许）。",
        "footer": "",
        "settings": [
            {
                "key": "Enabled",
                "display_name": "启用时间格式自定义",
                "type": "bool",
                "help_text": "开启后，聊天窗口中的时间将按下方格式重新渲染。关闭则 Mattermost 保持默认显示。",
                "placeholder": "",
                "default": true,
                "hosting": "",
                "secret": false
            },
            {
                "key": "TimeFormat",
                "display_name": "默认时间格式",
                "type": "text",
                "help_text": "支持令牌：YYYY YY MMMM MMM MM M DD D dddd ddd HH H hh h mm m ss s SSS A a Z ZZ X x，可用方括号包裹字面量如 [ 年 ]。示例：YYYY-MM-DD HH:mm:ss、YYYY年MM月DD日 HH:mm",
                "placeholder": "YYYY-MM-DD HH:mm",
                "default": "YYYY-MM-DD HH:mm",
                "hosting": "",
                "secret": false
            },
            {
                "key": "TimeZone",
                "display_name": "时区",
                "type": "text",
                "help_text": "留空表示使用浏览器本地时区；也可填写 IANA 时区名，例如 Asia/Shanghai、America/New_York、UTC。",
                "placeholder": "留空 = 浏览器本地时区",
                "default": "",
                "hosting": "",
                "secret": false
            },
            {
                "key": "ApplyTo",
                "display_name": "适用范围",
                "type": "dropdown",
                "help_text": "post：仅替换消息气泡上的时间（time.post__time）；all：替换页面中所有 \u003ctime\u003e 元素（含鼠标悬停提示、搜索结果、右侧边栏等）。",
                "placeholder": "",
                "default": "post",
                "options": [
                    {
                        "display_name": "仅消息时间（推荐）",
                        "value": "post"
                    },
                    {
                        "display_name": "页面内所有时间元素",
                        "value": "all"
                    }
                ],
                "hosting": "",
                "secret": false
            },
            {
                "key": "AllowUserOverride",
                "display_name": "允许用户自定义",
                "type": "bool",
                "help_text": "允许每个用户在自己的「设置」里覆盖默认格式与开关。",
                "placeholder": "",
                "default": true,
                "hosting": "",
                "secret": false
            }
        ],
        "sections": null
    }
}
`);

export default manifest;
