// This file is automatically generated. Do not modify it manually.

const manifest = JSON.parse(`
{
    "id": "com.example.customers-plugin",
    "name": "Customers Plugin",
    "description": "客户化定制插件：可自定义 Mattermost 聊天窗口中的时间显示格式（如 2026-09-15 09:42），支持管理员统一配置与用户个人偏好。",
    "homepage_url": "https://github.com/example/mattermost-plugin-customers",
    "support_url": "https://github.com/example/mattermost-plugin-customers/issues",
    "icon_path": "assets/icon.svg",
    "version": "0.4.3",
    "min_server_version": "10.0.0",
    "server": {
        "executables": {
            "darwin-amd64": "server/dist/plugin-darwin-amd64",
            "darwin-arm64": "server/dist/plugin-darwin-arm64",
            "linux-amd64": "server/dist/plugin-linux-amd64",
            "linux-arm64": "server/dist/plugin-linux-arm64",
            "windows-amd64": "server/dist/plugin-windows-amd64.exe"
        },
        "executable": ""
    },
    "webapp": {
        "bundle_path": "webapp/dist/main.js"
    },
    "settings_schema": {
        "header": "配置 Customers Plugin 的时间显示能力。管理员在此设置全站默认值，用户可在「设置 → 插件 → Customers Plugin」中按个人偏好覆盖（取决于下面是否允许）。",
        "footer": "",
        "settings": [
            {
                "key": "Enabled",
                "display_name": "启用时间格式自定义",
                "type": "bool",
                "help_text": "开启后，聊天窗口中的时间将按下方格式重新渲染。关闭则 Mattermost 保持默认显示。",
                "placeholder": "",
                "default": true,
                "hosting": "",
                "secret": false
            },
            {
                "key": "TimeFormat",
                "display_name": "默认时间格式",
                "type": "text",
                "help_text": "支持令牌：YYYY YY MMMM MMM MM M DD D dddd ddd HH H hh h mm m ss s SSS A a Z ZZ X x，可用方括号包裹字面量如 [ 年 ]。示例：YYYY-MM-DD HH:mm:ss、YYYY年MM月DD日 HH:mm",
                "placeholder": "YYYY-MM-DD HH:mm",
                "default": "YYYY-MM-DD HH:mm",
                "hosting": "",
                "secret": false
            },
            {
                "key": "TimeZone",
                "display_name": "时区",
                "type": "text",
                "help_text": "留空表示使用浏览器本地时区；也可填写 IANA 时区名，例如 Asia/Shanghai、America/New_York、UTC。",
                "placeholder": "留空 = 浏览器本地时区",
                "default": "",
                "hosting": "",
                "secret": false
            },
            {
                "key": "ApplyTo",
                "display_name": "适用范围",
                "type": "dropdown",
                "help_text": "post：仅替换消息气泡上的时间（time.post__time）；all：替换页面中所有 \u003ctime\u003e 元素（含鼠标悬停提示、搜索结果、右侧边栏等）。",
                "placeholder": "",
                "default": "post",
                "options": [
                    {
                        "display_name": "仅消息时间（推荐）",
                        "value": "post"
                    },
                    {
                        "display_name": "页面内所有时间元素",
                        "value": "all"
                    }
                ],
                "hosting": "",
                "secret": false
            },
            {
                "key": "AllowUserOverride",
                "display_name": "允许用户自定义",
                "type": "bool",
                "help_text": "允许每个用户在自己的「设置」里覆盖默认格式与开关。",
                "placeholder": "",
                "default": true,
                "hosting": "",
                "secret": false
            },
            {
                "key": "GroupedTimeEnabled",
                "display_name": "合并消息用浮框显示时间",
                "type": "bool",
                "help_text": "同一人连续发送的消息会被合并成一个消息块，从第 2 条起默认不显示时间。开启后，鼠标移到这些合并消息上会以浮框显示该条的完整时间（格式与上面一致）。",
                "placeholder": "",
                "default": true,
                "hosting": "",
                "secret": false
            },
            {
                "key": "GroupedTimePosition",
                "display_name": "浮框位置",
                "type": "dropdown",
                "help_text": "cursor：跟随鼠标指针；left：贴在该条消息的左侧；right：浮在该条消息的右上角。",
                "placeholder": "",
                "default": "cursor",
                "options": [
                    {
                        "display_name": "跟随鼠标（推荐）",
                        "value": "cursor"
                    },
                    {
                        "display_name": "消息左侧",
                        "value": "left"
                    },
                    {
                        "display_name": "消息右上角",
                        "value": "right"
                    }
                ],
                "hosting": "",
                "secret": false
            },
            {
                "key": "GroupedTimeHideInline",
                "display_name": "隐藏悬停时的内联时间",
                "type": "bool",
                "help_text": "Mattermost 默认会在鼠标悬停时把时间插进消息标题行。开启后隐藏它，避免与浮框重复显示同一时间，也避免顶开版面。",
                "placeholder": "",
                "default": true,
                "hosting": "",
                "secret": false
            },
            {
                "key": "ReadStatusEnabled",
                "display_name": "显示私信已讀/未讀标记",
                "type": "bool",
                "help_text": "开启后，私信（含群私信）中的每条消息会在右上角显示状态：未讀为黄色小圆圈 +「未讀」，已讀为绿色小圆圈 +「已讀」。公开与私有频道不显示标记。判定依据是看消息的人：别人发给你的消息，看「你」有没有读过；你发出去的消息，看「对方」有没有读过（群私信要所有人都读过才算已讀）。",
                "placeholder": "",
                "default": true,
                "hosting": "",
                "secret": false
            },
            {
                "key": "HistoryLockEnabled",
                "display_name": "启用新成员历史消息隔离",
                "type": "bool",
                "help_text": "开启后，新加入频道的成员将看不到其加入之前的历史消息。边界由服务端记录，前端负责隐藏。",
                "placeholder": "",
                "default": true,
                "hosting": "",
                "secret": false
            },
            {
                "key": "HistoryMode",
                "display_name": "历史可见范围",
                "type": "dropdown",
                "help_text": "since_join：只看该成员加入频道之后发送的消息（推荐）。recent_days：所有成员都只能看到最近 N 天的消息（N 见下方）。off：不做任何限制。",
                "placeholder": "",
                "default": "since_join",
                "options": [
                    {
                        "display_name": "只看加入之后（推荐）",
                        "value": "since_join"
                    },
                    {
                        "display_name": "只看最近 N 天",
                        "value": "recent_days"
                    },
                    {
                        "display_name": "不限制",
                        "value": "off"
                    }
                ],
                "hosting": "",
                "secret": false
            },
            {
                "key": "HistoryDays",
                "display_name": "最近 N 天的天数",
                "type": "text",
                "help_text": "仅在「历史可见范围 = 只看最近 N 天」时生效。填写正整数。",
                "placeholder": "7",
                "default": "7",
                "hosting": "",
                "secret": false
            },
            {
                "key": "LegacyMemberMode",
                "display_name": "存量成员如何处理",
                "type": "dropdown",
                "help_text": "插件只记录安装之后发生的加入事件。对于没有记录的成员：show_all 表示不限制（推荐，安装插件不会让老成员丢历史）；since_activation 表示以插件首次启用时间为边界。如需对个别成员精确设置，可用管理接口 POST /api/v1/history/boundary 回填。",
                "placeholder": "",
                "default": "show_all",
                "options": [
                    {
                        "display_name": "不限制（推荐）",
                        "value": "show_all"
                    },
                    {
                        "display_name": "以插件启用时间为边界",
                        "value": "since_activation"
                    }
                ],
                "hosting": "",
                "secret": false
            },
            {
                "key": "HideInSearch",
                "display_name": "同时隐藏搜索与右侧栏中的历史消息",
                "type": "bool",
                "help_text": "开启后，被隐藏的消息在搜索结果、右侧线程、置顶与已保存列表中同样不可见。",
                "placeholder": "",
                "default": true,
                "hosting": "",
                "secret": false
            },
            {
                "key": "HistoryNoticeEnabled",
                "display_name": "显示隐藏提示",
                "type": "bool",
                "help_text": "在频道顶部显示一条提示，说明更早的消息已被隐藏。",
                "placeholder": "",
                "default": true,
                "hosting": "",
                "secret": false
            },
            {
                "key": "HistoryNoticeText",
                "display_name": "隐藏提示文案",
                "type": "text",
                "help_text": "显示在频道顶部的提示文字。",
                "placeholder": "此消息及之前的消息发送于你加入本频道之前，已隐藏",
                "default": "此消息及之前的消息发送于你加入本频道之前，已隐藏",
                "hosting": "",
                "secret": false
            },
            {
                "key": "ExemptSystemAdmins",
                "display_name": "系统管理员不受限制",
                "type": "bool",
                "help_text": "开启后，拥有「管理服务器」权限的用户仍可看到完整历史，便于排障。",
                "placeholder": "",
                "default": false,
                "hosting": "",
                "secret": false
            }
        ],
        "sections": null
    }
}
`);

export default manifest;
